from idlelib.config import idleConf as idleConf
from tkinter import Event, Misc, Text

class History:
    text: Text
    history: list[str]
    prefix: str | None
    pointer: int | None
    cyclic: bool
    def __init__(self, text: Text) -> None: ...
    def history_next(self, event: Event[Misc] | None) -> str: ...
    def history_prev(self, event: Event[Misc] | None) -> str: ...
    def fetch(self, reverse: bool) -> None: ...
    def store(self, source: str) -> None: ...
