from collections.abc import Callable
from idlelib.config import idleConf as idleConf
from idlelib.hyperparser import HyperParser as HyperParser
from idlelib.pyshell import PyShellEditorWindow
from tkinter import Event, Misc, Text

CHECK_DELAY: int

class ParenMatch:
    RESTORE_VIRTUAL_EVENT_NAME: str
    RESTORE_SEQUENCES: tuple[str, ...]
    STYLE: str
    FLASH_DELAY: int
    BELL: bool
    HILITE_CONFIG: dict[str, str]
    editwin: PyShellEditorWindow
    text: Text
    counter: int
    is_restore_active: bool
    def __init__(self, editwin: PyShellEditorWindow) -> None: ...
    @classmethod
    def reload(cls) -> None: ...
    def activate_restore(self) -> None: ...
    def deactivate_restore(self) -> None: ...
    def flash_paren_event(self, event: Event[Misc]) -> str: ...
    def paren_closed_event(self, event: Event[Misc]) -> None: ...
    def finish_paren_event(self, indices: tuple[str, str] | None) -> None: ...
    def restore_event(self, event: Event[Misc] | None = ...) -> None: ...
    def handle_restore_timer(self, timer_count: int) -> None: ...
    def create_tag_opener(self, indices: tuple[str, str]) -> None: ...
    def create_tag_parens(self, indices: tuple[str, str]) -> None: ...
    def create_tag_expression(self, indices: tuple[str, str]) -> None: ...
    tagfuncs: dict[str, Callable[[tuple[str, str]], None]]
    def set_timeout_none(self) -> None: ...
    def set_timeout_last(self) -> None: ...
