from _tkinter import Tcl_Obj
from code import InteractiveInterpreter
from collections.abc import Callable
from idlelib import (
    debugger as debugger,
    debugger_r as debugger_r,
    replace as replace,
    rpc as rpc,
)
from idlelib.colorizer import ColorDelegator as ColorDelegator
from idlelib.config import idleConf as idleConf
from idlelib.debugger import Debugger
from idlelib.delegator import Delegator as Delegator
from idlelib.editor import (
    EditorWindow as EditorWindow,
    fixwordbreaks as fixwordbreaks,
)
from idlelib.filelist import FileList as FileList
from idlelib.history import History as History
from idlelib.outwin import OutputWindow as OutputWindow
from idlelib.run import (
    StdInputFile as StdInputFile,
    StdOutputFile as StdOutputFile,
    fix_scaling as fix_scaling,
    idle_formatwarning as idle_formatwarning,
)
from idlelib.sidebar import ShellSidebar as ShellSidebar
from idlelib.squeezer import Squeezer as Squeezer
from idlelib.undo import UndoDelegator as UndoDelegator
from subprocess import Popen
from tkinter import *  # noqa: F403
from tkinter import Event, Misc, Tk, Widget
from types import CodeType
from typing import TextIO

root: Tk
flist: PyShellFileList
use_subprocess: bool
HOST: str
PORT: int
eof: str
warning_stream: TextIO | None
usage_msg: str
_warnings_showwarning: (
    Callable[
        [Warning | str, type[Warning], str, int, TextIO | None, str | None],
        None,
    ]
    | None
)

def idle_showwarning(
    message: str,
    category: BaseException,
    filename: str,
    lineno: int,
    file: TextIO | None = ...,
    line: str | None = ...,
) -> None: ...
def capture_warnings(capture: bool) -> None: ...
def extended_linecache_checkcache(
    filename: str | None = ...,
    orig_checkcache: Callable[[str], None] = ...,
) -> None: ...

class PyShellEditorWindow(EditorWindow):
    breakpoints: list[int]
    breakpointPath: str
    flist: PyShellFileList  # type: ignore[mutable-override]
    root: Tk  # type: ignore[mutable-override]
    def __init__(self, *args: PyShellFileList | Tk | str | None) -> None: ...
    rmenu_specs: list[tuple[str | None, str | None, str | None]]
    def color_breakpoint_text(self, color: bool = ...) -> None: ...
    def set_breakpoint(self, lineno: int) -> None: ...
    def set_breakpoint_event(
        self,
        event: Event[Misc] | None = ...,
    ) -> None: ...
    def clear_breakpoint_event(
        self,
        event: Event[Misc] | None = ...,
    ) -> None: ...
    def clear_file_breaks(self) -> None: ...
    def store_file_breaks(self) -> None: ...
    def restore_file_breaks(self) -> None: ...
    def update_breakpoints(self) -> None: ...
    def ranges_to_linenumbers(
        self,
        ranges: tuple[Tcl_Obj, ...],
    ) -> list[int]: ...

class PyShellFileList(FileList):
    EditorWindow: type[PyShellEditorWindow]  # type: ignore[override]
    pyshell: PyShell | None
    def open_shell(
        self,
        event: Event[Misc] | None = ...,
    ) -> PyShell | None: ...

class ModifiedColorDelegator(ColorDelegator):
    def recolorize_main(self) -> None: ...
    def removecolors(self) -> None: ...

class ModifiedUndoDelegator(UndoDelegator):
    def insert(
        self,
        index: str,
        chars: str,
        tags: str | None = ...,
    ) -> None: ...
    def delete(
        self,
        index1: str | float | Tcl_Obj | Widget,
        index2: str | float | Tcl_Obj | Widget | None = ...,
    ) -> None: ...
    def undo_event(self, event: Event[Misc]) -> None: ...  # type: ignore[override]

class UserInputTaggingDelegator(Delegator):
    def insert(
        self,
        index: str | float | Tcl_Obj | Widget,
        chars: str,
        tags: str | None = ...,
    ) -> None: ...

class MyRPCClient(rpc.RPCClient):
    def handle_EOF(self) -> None: ...

def restart_line(width: int, filename: str | None) -> str: ...

class ModifiedInterpreter(InteractiveInterpreter):
    tkconsole: object
    restarting: bool
    subprocess_arglist: list[str] | None
    port: int
    original_compiler_flags: int
    def __init__(self, tkconsole: object) -> None: ...
    rpcclt: MyRPCClient | None
    rpcsubproc: Popen[str] | None
    def spawn_subprocess(self) -> None: ...
    def build_subprocess_arglist(self) -> list[str]: ...
    def start_subprocess(self) -> MyRPCClient | None: ...
    def restart_subprocess(
        self,
        with_cwd: bool = ...,
        filename: str = ...,
    ) -> MyRPCClient | None: ...
    def interrupt_subprocess(self) -> None: ...
    def kill_subprocess(self) -> None: ...
    def terminate_subprocess(self) -> None: ...
    def transfer_path(self, with_cwd: bool = ...) -> None: ...
    active_seq: int | None
    def poll_subprocess(self) -> None: ...
    debugger: Debugger | None
    def setdebugger(self, debugger: Debugger | None) -> None: ...
    def getdebugger(self) -> Debugger | None: ...
    def open_remote_stack_viewer(self) -> None: ...
    def remote_stack_viewer(self) -> None: ...
    gid: int
    def execsource(self, source: str) -> None: ...
    def execfile(self, filename: str, source: str | None = ...) -> None: ...
    def runsource(self, source: str) -> bool: ...  # type: ignore[override]
    def stuffsource(self, source: str) -> str: ...
    def prepend_syspath(self, filename: str) -> None: ...
    def showsyntaxerror(
        self,
        filename: str | None = ...,
        **kwargs: str,
    ) -> None: ...
    def showtraceback(self) -> None: ...
    def checklinecache(self) -> None: ...
    def runcommand(
        self,
        code: str,
    ) -> bool: ...  # Actually returns int object but that is a hack because of int truthyness
    def runcode(self, code: CodeType) -> None: ...
    def write(self, s: str) -> int: ...  # type: ignore[override]
    def display_port_binding_error(self) -> None: ...
    def display_no_subprocess_error(self) -> None: ...
    def display_executing_dialog(self) -> None: ...

class PyShell(OutputWindow):
    shell_title: str
    ColorDelegator: type[ModifiedColorDelegator]
    UndoDelegator: type[ModifiedUndoDelegator]
    menu_specs: list[tuple[str, str]]
    rmenu_specs: list[tuple[str, str]]  # type: ignore[assignment]
    allow_line_numbers: bool
    user_input_insert_tags: str  # type: ignore[mutable-override]
    history: History
    History: type[History]
    shell_sidebar: ShellSidebar
    ShellSidebar: type[ShellSidebar]
    interp: ModifiedInterpreter
    root: Tk  # type: ignore[mutable-override]
    flist: PyShellFileList  # type: ignore[mutable-override]
    usetabs: bool
    indentwidth: int
    sys_ps1: str
    prompt_last_line: str
    prompt: str
    squeezer: Squeezer
    Squeezer: type[Squeezer]
    save_stdout: TextIO
    save_stderr: TextIO
    save_stdin: TextIO
    stdin: StdInputFile
    stdout: StdInputFile
    stderr: StdInputFile
    console: StdOutputFile
    pollinterval: int
    def __init__(self, flist: PyShellFileList | None = ...) -> None: ...
    def ResetFont(self) -> None: ...
    def ResetColorizer(self) -> None: ...
    def replace_event(self, event: Event[Misc] | None) -> str: ...
    def get_standard_extension_names(self) -> list[str]: ...
    def get_prompt_text(
        self,
        first: str | float | Tcl_Obj | Widget,
        last: str | float | Tcl_Obj | Widget,
    ) -> str: ...
    def copy_with_prompts_callback(
        self,
        event: Event[Misc] | None = ...,
    ) -> None: ...
    reading: bool
    executing: bool
    canceled: bool
    endoffile: bool
    closing: bool
    def set_warning_stream(self, stream: TextIO) -> None: ...
    def get_warning_stream(self) -> TextIO: ...
    def toggle_debugger(
        self,
        event: Event[Misc] | None = ...,
    ) -> str | None: ...
    def set_debugger_indicator(self) -> None: ...
    def toggle_jit_stack_viewer(
        self,
        event: Event[Misc] | None = ...,
    ) -> None: ...
    def close_debugger(self) -> None: ...
    def open_debugger(self) -> None: ...
    def debug_menu_postcommand(self) -> None: ...
    def beginexecuting(self) -> None: ...
    def endexecuting(self) -> None: ...
    def close(self) -> str | None: ...
    def ispythonsource(self, filename: str) -> bool: ...
    def short_title(self) -> str: ...
    SPLASHLINE: str
    def begin(self) -> bool: ...
    def stop_readline(self) -> None: ...
    def readline(self) -> str: ...
    def isatty(self) -> bool: ...
    def cancel_callback(
        self,
        event: Event[Misc] | None = ...,
    ) -> str | None: ...
    def eof_callback(self, event: Event[Misc]) -> str | None: ...
    def linefeed_callback(self, event: Event[Misc]) -> str: ...
    def enter_callback(self, event: Event[Misc]) -> str | None: ...
    def recall(self, s: str, event: Event[Misc]) -> None: ...
    def runit(self) -> None: ...
    def open_stack_viewer(self, event: Event[Misc] | None = ...) -> None: ...
    def view_restart_mark(self, event: Event[Misc] | None = ...) -> None: ...
    def restart_shell(self, event: Event[Misc] | None = ...) -> None: ...
    def showprompt(self) -> None: ...
    def show_warning(self, msg: str) -> None: ...
    def resetoutput(self) -> None: ...
    def write(self, s: str, tags: tuple[str, ...] = ...) -> int: ...  # type: ignore[override]
    def rmenu_check_cut(self) -> str: ...
    def rmenu_check_paste(self) -> str: ...
    def squeeze_current_text_event(
        self,
        event: Event[Misc] | None = ...,
    ) -> None: ...
    def on_squeezed_expand(
        self,
        index: str | float | Tcl_Obj | Widget,
        text: str,
        tags: str | None,
    ) -> None: ...

def fix_x11_paste(root: Tk) -> None: ...
def main() -> None: ...
