from idlelib import macosx as macosx
from tkinter import *  # noqa: F403
from tkinter import Event, Listbox, Menu, Misc
from tkinter.ttk import Frame as _ttk_Frame, Scrollbar as _ttk_Scrollbar
from typing import Any

class ScrolledList:
    default: str
    master: Misc
    frame: _ttk_Frame
    vbar: _ttk_Scrollbar
    listbox: Listbox
    def __init__(self, master: Misc, **options: Any) -> None: ...
    def close(self) -> None: ...
    empty: int
    def clear(self) -> None: ...
    def append(self, item: str) -> None: ...
    def get(self, index: int) -> str: ...
    def click_event(self, event: Event[Misc]) -> str: ...
    def double_click_event(self, event: Event[Misc] | None) -> str: ...
    menu: Menu | None
    def popup_event(self, event: Event[Misc] | None) -> str | None: ...
    def make_menu(self) -> None: ...
    def up_event(self, event: Event[Misc] | None) -> str: ...
    def down_event(self, event: Event[Misc] | None) -> str: ...
    def select(self, index: int) -> None: ...
    def fill_menu(self) -> None: ...
    def on_select(self, index: int) -> None: ...
    def on_double(self, index: int) -> None: ...
